In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.core.pylabtools import figsize
import seaborn as sns

In [2]:
df = pd.read_csv('UEA RESULTS.csv')
df = df[['Supplier ID', 'Mw', 'SMILES', 'TO Displacement', 'STDEV' ]]
df.head()

,Supplier ID,Mw,SMILES,TO Displacement,STDEV
0,RAL541,444.57,O=S(N(C1=C2C=CC=C1)C3=C2C[C@H]4[C@H](S(=O)(C)=...,-10.79%,3.86%
1,RAL542,405.51,O=S([C@@H]1C[C@H]2C(N(CC#N)C3=C4C=CC=C3)=C4C[C...,6.84%,4.71%
2,RAL554,247.35,O[C@H]1[C@@H]2C[C@@H](S(=O)(C)=O)[C@@H](N2C(C)...,1.88%,11.81%
3,RAL577,325.43,CC(C)N1[C@H]2CC[C@@H](OC3=CC=NC=N3)[C@@H]1C[C@...,6.19%,5.91%
4,RAL559,232.34,CN[C@H]1[C@@H]2C[C@@H](S(=O)(C)=O)[C@@H](N2C)CC1,-26.61%,10.11%

In [3]:
df1 = pd.read_csv('GERMANY PURITY.csv')
df1 = df1[['Supplier_ID', 'Purity (%) @LCMS']]
df1.head()

  Supplier_ID  Purity (%) @LCMS
0      RAL541              87.0
1      RAL571              63.0
2      RAL386              95.0
3      RAL575             100.0
4      RAL365              62.0

In [4]:
#rename
df1.rename(columns={'Supplier_ID': 'Supplier ID'}, inplace=True)

In [5]:
#merge data based off Supplier ID
UEA_results = pd.merge(df, df1, on = 'Supplier ID')
UEA_results.head()

,Supplier ID,Mw,SMILES,TO Displacement,STDEV,Purity (%) @LCMS
0,RAL541,444.57,O=S(N(C1=C2C=CC=C1)C3=C2C[C@H]4[C@H](S(=O)(C)=...,-10.79%,3.86%,87.0
1,RAL542,405.51,O=S([C@@H]1C[C@H]2C(N(CC#N)C3=C4C=CC=C3)=C4C[C...,6.84%,4.71%,98.0
2,RAL554,247.35,O[C@H]1[C@@H]2C[C@@H](S(=O)(C)=O)[C@@H](N2C(C)...,1.88%,11.81%,100.0
3,RAL577,325.43,CC(C)N1[C@H]2CC[C@@H](OC3=CC=NC=N3)[C@@H]1C[C@...,6.19%,5.91%,97.0
4,RAL559,232.34,CN[C@H]1[C@@H]2C[C@@H](S(=O)(C)=O)[C@@H](N2C)CC1,-26.61%,10.11%,100.0

In [6]:
                            ### repeat procedure on germany compounds ###
    
#open germany compound data, drop unwanted and rename
g_comp = pd.read_csv('Hedghog germany.csv')
g_comp = g_comp[['Supplier_ID/Enso name', '% activity@ Autophagy', '% activity@ Autophagy rapamycin', '% activity@ Hedgehog osteogenesis','% activity@ Hedgehog osteogenesis-Viability', 'IC50 (µM)@ Hedgehog osteogenesis', 'IC50 (µM)@ Hedgehog osteogenesis-Viability']]
g_comp.rename(columns={'Supplier_ID/Enso name': 'Supplier ID'}, inplace=True)

#combine germany and uea data
germany_and_uea = pd.merge(g_comp, UEA_results, on = 'Supplier ID')

In [7]:
                                    ### repeat procedure###
CT_comp = pd.read_csv('Mtb MICs.csv')
CT_comp.head()

,Position,Supplier,Supplier ID,SMILES,VISUAL MIC90 7D 7H9 GLU CAS TX (uM),VISUAL MIC90 7D 7H9 GLU ADC TW (uM),Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,A1,UEA compounds,RAL541,O=S(N(C1=C2C=CC=C1)C3=C2C[C@H]4[C@H](S(=O)(C)=...,62.5,> 125,NaN,NaN,NaN,NaN,NaN
1,A2,UEA compounds,RAL542,O=S([C@@H]1C[C@H]2C(N(CC#N)C3=C4C=CC=C3)=C4C[C...,> 125,> 125,NaN,NaN,NaN,NaN,NaN
2,A3,UEA compounds,RAL554,O[C@H]1[C@@H]2C[C@@H](S(=O)(C)=O)[C@@H](N2C(C)...,> 125,> 125,NaN,NaN,NaN,NaN,NaN
3,A4,UEA compounds,RAL577,CC(C)N1[C@H]2CC[C@@H](OC3=CC=NC=N3)[C@@H]1C[C@...,> 125,> 125,NaN,NaN,NaN,NaN,NaN
4,A5,UEA compounds,RAL559,CN[C@H]1[C@@H]2C[C@@H](S(=O)(C)=O)[C@@H](N2C)CC1,> 125,> 125,NaN,NaN,NaN,NaN,NaN

In [8]:
#CT_comp = CT_comp[['Supplier ID', 'VISUAL MIC90 7D 7H9 GLU CAS TX (uM)', 'VISUAL MIC90 7D 7H9 GLU ADC TW (uM)' ]]
CT_comp = CT_comp.drop(['Supplier', 'Position', 'SMILES','Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10' ],axis=1)

In [9]:
#combine data
germany_and_uea_CT = pd.merge(CT_comp, germany_and_uea, on = 'Supplier ID')
germany_and_uea_CT.head()

,Supplier ID,VISUAL MIC90 7D 7H9 GLU CAS TX (uM),VISUAL MIC90 7D 7H9 GLU ADC TW (uM),% activity@ Autophagy,% activity@ Autophagy rapamycin,% activity@ Hedgehog osteogenesis,% activity@ Hedgehog osteogenesis-Viability,IC50 (µM)@ Hedgehog osteogenesis,IC50 (µM)@ Hedgehog osteogenesis-Viability,Mw,SMILES,TO Displacement,STDEV,Purity (%) @LCMS
0,RAL541,62.5,> 125,75.0,74.0,35.0,35.0,5.7\n5.7\n4.4,\ninactive\n> 10\n> 10,444.57,O=S(N(C1=C2C=CC=C1)C3=C2C[C@H]4[C@H](S(=O)(C)=...,-10.79%,3.86%,87.0
1,RAL542,> 125,> 125,82.0,75.0,43.0,83.0,4.2\n5.6\n> 10,\ninactive\ninactive\ninactive,405.51,O=S([C@@H]1C[C@H]2C(N(CC#N)C3=C4C=CC=C3)=C4C[C...,6.84%,4.71%,98.0
2,RAL554,> 125,> 125,135.0,114.0,120.0,83.0,NaN,NaN,247.35,O[C@H]1[C@@H]2C[C@@H](S(=O)(C)=O)[C@@H](N2C(C)...,1.88%,11.81%,100.0
3,RAL577,> 125,> 125,97.0,116.0,119.0,98.0,NaN,NaN,325.43,CC(C)N1[C@H]2CC[C@@H](OC3=CC=NC=N3)[C@@H]1C[C@...,6.19%,5.91%,97.0
4,RAL559,> 125,> 125,88.0,83.0,94.0,15.0,NaN,NaN,232.34,CN[C@H]1[C@@H]2C[C@@H](S(=O)(C)=O)[C@@H](N2C)CC1,-26.61%,10.11%,100.0

In [10]:
                                ### repeat procedure###
CT_comp_2= pd.read_csv('Pf IC50s.csv')
CT_comp_2 = CT_comp_2[['Supplier ID', 'Unnamed: 10','NF54 test 1: IC50 (nM)', 'Unnamed: 12',  'NF54 test 2: IC50 (nM)', 'Unnamed: 14', 'Average NF54: IC50 (nM)' ]]

In [11]:
#combine data
germany_and_uea_CT = pd.merge(CT_comp_2, germany_and_uea_CT, on = 'Supplier ID')
#how='outer', left_index=True, right_index=True,
germany_and_uea_CT.head()

,Supplier ID,Unnamed: 10,NF54 test 1: IC50 (nM),Unnamed: 12,NF54 test 2: IC50 (nM),Unnamed: 14,Average NF54: IC50 (nM),VISUAL MIC90 7D 7H9 GLU CAS TX (uM),VISUAL MIC90 7D 7H9 GLU ADC TW (uM),% activity@ Autophagy,% activity@ Autophagy rapamycin,% activity@ Hedgehog osteogenesis,% activity@ Hedgehog osteogenesis-Viability,IC50 (µM)@ Hedgehog osteogenesis,IC50 (µM)@ Hedgehog osteogenesis-Viability,Mw,SMILES,TO Displacement,STDEV,Purity (%) @LCMS
0,RAL541,>,6000.0,>,6000.0,>,6000.0,62.5,> 125,75.0,74.0,35.0,35.0,5.7\n5.7\n4.4,\ninactive\n> 10\n> 10,444.57,O=S(N(C1=C2C=CC=C1)C3=C2C[C@H]4[C@H](S(=O)(C)=...,-10.79%,3.86%,87.0
1,RAL542,>,6000.0,>,6000.0,>,6000.0,> 125,> 125,82.0,75.0,43.0,83.0,4.2\n5.6\n> 10,\ninactive\ninactive\ninactive,405.51,O=S([C@@H]1C[C@H]2C(N(CC#N)C3=C4C=CC=C3)=C4C[C...,6.84%,4.71%,98.0
2,RAL554,>,6000.0,>,6000.0,>,6000.0,> 125,> 125,135.0,114.0,120.0,83.0,NaN,NaN,247.35,O[C@H]1[C@@H]2C[C@@H](S(=O)(C)=O)[C@@H](N2C(C)...,1.88%,11.81%,100.0
3,RAL577,>,6000.0,>,6000.0,>,6000.0,> 125,> 125,97.0,116.0,119.0,98.0,NaN,NaN,325.43,CC(C)N1[C@H]2CC[C@@H](OC3=CC=NC=N3)[C@@H]1C[C@...,6.19%,5.91%,97.0
4,RAL559,>,6000.0,>,6000.0,>,6000.0,> 125,> 125,88.0,83.0,94.0,15.0,NaN,NaN,232.34,CN[C@H]1[C@@H]2C[C@@H](S(=O)(C)=O)[C@@H](N2C)CC1,-26.61%,10.11%,100.0

In [12]:
llama = pd.read_csv('LLAMA SCREENING CMPS.csv')
llama = llama.drop(['Lipinski rule-of-5 failures','Plane of best fit', 'Canonical SMILES', 'Murcko framework', 'Murcko framework with alpha atoms','Type','Parent molecule 1 ID', 'Parent molecule 1 canonical SMILES', 'Parent molecule 2 ID', 'Parent molecule 2 canonical SMILES', 'Product of reaction' ], axis=1)
llama.head()

,Molecule ID,RMM,AlogP,Lead-likeness penalty,tPSA,Carbon sp3 fraction,PMI x (I1),PMI y (I2),Heavy atoms,Aliphatic rings,Aromatic rings,Heteroatoms,Chiral centres,Rotatable bonds
0,46,354.440,0.09,0.0,69.64,0.647059,0.29429,0.88841,24.0,3.0,1.0,7.0,6.0,3.0
1,47,299.361,0.30,0.0,66.40,0.571429,0.25676,0.88021,20.0,2.0,1.0,6.0,5.0,2.0
2,48,367.435,0.86,1.0,74.68,0.611111,0.46003,0.89045,25.0,3.0,1.0,7.0,5.0,4.0
3,49,371.424,0.27,1.0,83.91,0.588235,0.50701,0.86133,25.0,2.0,1.0,8.0,5.0,5.0
4,50,425.497,1.28,3.0,89.34,0.388889,0.48128,0.83397,28.0,2.0,2.0,10.0,4.0,4.0

In [13]:
#round to two decimal places
llama['RMM'] = llama['RMM'].astype(float).round(2)
llama.head()

,Molecule ID,RMM,AlogP,Lead-likeness penalty,tPSA,Carbon sp3 fraction,PMI x (I1),PMI y (I2),Heavy atoms,Aliphatic rings,Aromatic rings,Heteroatoms,Chiral centres,Rotatable bonds
0,46,354.44,0.09,0.0,69.64,0.647059,0.29429,0.88841,24.0,3.0,1.0,7.0,6.0,3.0
1,47,299.36,0.30,0.0,66.40,0.571429,0.25676,0.88021,20.0,2.0,1.0,6.0,5.0,2.0
2,48,367.44,0.86,1.0,74.68,0.611111,0.46003,0.89045,25.0,3.0,1.0,7.0,5.0,4.0
3,49,371.42,0.27,1.0,83.91,0.588235,0.50701,0.86133,25.0,2.0,1.0,8.0,5.0,5.0
4,50,425.50,1.28,3.0,89.34,0.388889,0.48128,0.83397,28.0,2.0,2.0,10.0,4.0,4.0

In [14]:
#rename column
llama.rename(columns={'RMM': 'Mw'}, inplace=True)

In [15]:
#merge results
ALL_and_llama = pd.merge(llama, germany_and_uea_CT, on = 'Mw')
#save data
ALL_and_llama.to_csv('ALL_and_llama.csv', sep=',')